### ISSUE TITLE
cannot import name 'NNPotential' from 'maml.apps.pes'

### ISSUE THREAD

**Issue by Ruskinkot1** [materialsvirtuallab/maml#155]
Hello! 
I've got a problem at initials state while importing potentials
`from maml.apps.pes import NNPotential
`
`ImportError: cannot import name 'NNPotential' from 'maml.apps.pes' (//anaconda3/lib/python3.7/site-packages/maml/apps/pes/__init__.py)`
 
The same thing with other potentials

Thanks in advance!

**Comment by chc273** [comment]
Could you try a fresh installation from the GitHub repo? you can git clone the repo first and then use  “python setup.py install” @Ruskinkot1
