### ISSUE TITLE
ImportError: cannot import name 'export_saved_model' from 'tensorflow.python.keras.saving.saved_model'

### ISSUE THREAD

**Issue by vishankkumar** [materialsvirtuallab/maml#163]
Hi,

I was trying to run one of the notebooks and received this error while importing:

`ImportError: cannot import name 'export_saved_model' from 'tensorflow.python.keras.saving.saved_model' (/home/vishank-hp/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/__init__.py)
`
For installation, I tried both the methods:
1. Forking the repository and `python setup.py develop`
2. `pip install maml`

Would you please let me know if I do have to install some dependencies manually? or I am missing a step.

Thanks

**Comment by chc273** [comment]
@vishankkumar please be very specific and make sure how can I reproduce the problem. As a starter, which notebook did you run and where did the error happen

**Comment by vishankkumar** [comment]
Sure, I was trying to run the notebook `model/garnet_formation_energy.ipynb` and the error occurred just after executing the first cell to import the libraries.

Even running a single import `from maml.models import ModelWithSklearn` can reproduce the error.

Let me know if you need some other information. Just FYI, I am using python 3.7.7

**Comment by chc273** [comment]
@vishankkumar the problem was caused by the renaming of some classes. I have updated the notebook in github repo. Please have a look, it should solve the problem

**Comment by vishankkumar** [comment]
Thank you for the correction, however now I am getting a module error: 
`ModuleNotFoundError: No module named 'megnet'`
while importing `from maml.models import SKLModel`

I have done a fresh installation of maml via pip in a new conda environment

**Comment by chc273** [comment]
@vishankkumar that's one of the dependency. You can just install megnet via pip.

**Comment by vishankkumar** [comment]
@chc273 perfect, apart from some deprecated warnings, now the notebook worked fine. Thanks for your help.
