### ISSUE TITLE
Installing GAP and NNP dependencies

### ISSUE THREAD

**Issue by vishankkumar** [materialsvirtuallab/maml#166]
Hi,

I was trying to run the example of PES with GAP fitting, and would like to know how I can interface MAML code with GAP. I have installed quippy with GAP already but do not know how to let maml code direct at the correct file/location to look for GAP capabilities.

Thanks

**Comment by YunxingZuo** [comment]
Hi @vishankkumar 

Thanks for your interest in using PES module!

Please add the capabilities (e.g., gap_fit for GAP fitting) in your environment path. The fit method works by detecting the executable automatically and run it in the background. If the fit method doesn't detect the executable, it will throw an error of "gap_fit has not been found."

**Comment by vishankkumar** [comment]
Dear @YunxingZuo ,

Thank you for your response. I managed to get the Gap_fit executable linked properly, however I do not know how to link nnp train from n2p2. I have compiled nnp-train in the Shared mode.

Thanks for your response.
Vishank

**Comment by vishankkumar** [comment]
I got it worked, I just had to add the `lib/` to `LD_LIBRARY_PATH`. However, I am getting an error in the example `notebooks/pes/nnp/`. I have attached the snapshot of the error. Would you please let me know what is the reason for that.
![screenshot_NNP_Error](https://user-images.githubusercontent.com/32134010/110124086-f7885800-7dc1-11eb-8ef2-b903b6e6166f.png)

**Comment by YunxingZuo** [comment]
@vishankkumar Could you please update the maml to the newest version (i.e., 0.0.4)? I believe this problem has been solved in #194.

**Comment by vishankkumar** [comment]
@YunxingZuo  Thanks for the suggestion, it worked after pulling the latest version from github.
