### ISSUE TITLE
mpi for NNP

### ISSUE THREAD

**Issue by Akram-Ibrahim** [materialsvirtuallab/maml#216]
I wonder if the parallelization of n2p2 through mpi is transferred and can be used in the maml package.

**Comment by YunxingZuo** [comment]
Currently, the parallelization of n2p2 is not implemented in maml package yet. We will implement the functionality very soon. One suggestion I have is that you can go to the execution file (path_to_maml/apps/pes/_nnp.py) in your own installed package and adjust the cores used. E.g., If you attempt to use 24 cores in the training you can add `subprocess.Popen(["mpirun", "-np", 24, "nnp-train"], stdout=open(output, "w"), stderr=subprocess.PIPE)` to line 752.

**Comment by Akram-Ibrahim** [comment]
Nice! Thank you @YunxingZuo.
