### ISSUE TITLE
Potential file from NNP to Lammps

### ISSUE THREAD

**Issue by Akram-Ibrahim** [materialsvirtuallab/maml#254]
Hi! 

I wonder if there's a functionality in maml to extract a NNP potential file (in the Lammps) format after training within the maml 
framework, in order to run further Lammps simulations. 

Thanks in advance!

**Comment by JiQi535** [comment]
Suppose you have trained your own NNP or loaded a trained NNP and named it as `nnp_loaded`, you can write the parameters into files by the `write_param` function. So `nnp_loaded.write_param()` will write the parameter files into your working folder. Maml has this function for all its supported MLIAPs.

You may also have a look at the [MLIAP notebooks](https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/nnp/example.ipynb), where a trained NNP is provided as an example to play with.

**Comment by Akram-Ibrahim** [comment]
Thank you!
