### ISSUE TITLE
general describers can be rewritten

### ISSUE THREAD

**Issue by chc273** [materialsvirtuallab/maml#3]
There are two describers in general.py, namely MultiDescriber and FuncGenerator. 

The MultiDescriber works similarly to a sklearn Pipeline. I think we can redo this using sklearn pipeline to get a more robust version. 

The FuncGenertor relies on the `eval` function to deserialize a function. It requires that the function to be defined somewhere in the script or in the general.py module. It is not very robust.  It would be nice to rewrite it and use utilities `maml.utils` to deserialize the functions.

**Comment by shyuep** [comment]
This is fine. But the deserialization routinues in maml are a bit strange. I am not even clear what is the difference between those and those implemented in monty. I think we should consider whether we really need serialziation routinues specific to maml.

**Comment by chc273** [comment]
I agree. We can delete them and use monty for those tasks. So far, all the functionalities can be achieved by monty.
