### ISSUE TITLE
An error of source code 

### ISSUE THREAD

**Issue by yufeib** [materialsvirtuallab/maml#32]
The  method parameter 'model_fname' of SNAPotential.model.save(**model_fname**=filename) seems not match with sklearn?? cause when it called, an error was raised。It should be 'filename'??

**Comment by YunxingZuo** [comment]
@yufeib Thanks for pointing out! In practice, the `save` method is rarely used when comes to saving the trained Potential. Instead, users are encouraged to use the consistent `write_param` and `load_config` methods to write and read the parameter files. Please refer to [notebook example](https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/snap/example.ipynb). To reduce the confusion, the `save` methods in `pes` module have been removed.
