### ISSUE TITLE
what happens when BOWSR selects parameters corresponding to a structure with isolated atoms.

### ISSUE THREAD

**Issue by CompRhys** [materialsvirtuallab/maml#320]
The pre-trained MEGNet cannot handle materials with atoms that are isolated with 5\AA, when using BOSWR the GP can select such structures as candidates what happens? I cannot find any error handling in the app code presented here for megnet variant

**Comment by chc273** [comment]
@CompRhys This is a good point. Currently, we just let the optimization fail. The users will need to handle the errors themselves. Would love to see if there are any alternative ideas of how this can be better handled. We do not have the error handling codes for now to avoid unexpected behaviors

**Comment by rhys-exabyte** [comment]
Ahh okay, I’ve been toying around with a reimplementation of BOWSR using a different black-box optimisation algorithm and using aflow to do the symmetry work meaning total code should be <200 lines but was hitting failure modes in some of my test systems. At the moment I am just filling a constant but this is contrary to the GP smoothness assumption so wondered if you already had a solution. I will let you know if I get a good answer to how best to handle this case.

**Comment by CompRhys** [comment]
I've been toying around with a reimplementation of `BOWSR` as I want to compare against my `Wren` model. I am using different black-box optimisation algorithm and using aflow to do the symmetry work meaning total code should be <200 lines so was quite happy with it but then started hitting this failure modes in some of my more complicated test systems. At the moment I am just filling a constant but this is contrary to the GP smoothness assumption so wondered if you already had a solution. I will let you know if I get a good answer.
