### ISSUE TITLE
ModuleNotFoundError: No module named 'bowsr'

### ISSUE THREAD

**Issue by zhigangmei** [materialsvirtuallab/maml#326]
Hi, 

I had some problems to run the notebooks of cgcnn_example.ipynb and megnet_example.ipynb.

I had the similar error messages for both notebooks:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/0c/rcgf90kd6z9c7yc0p_tpffl81l1jxs/T/ipykernel_90244/3049958724.py in <module>
----> 1 from bowsr.model.cgcnn import CGCNN
      2 from bowsr.optimizer import BayesianOptimizer
      3 from pymatgen.core.periodic_table import get_el_sp
      4 model = CGCNN()
      5 

ModuleNotFoundError: No module named 'bowsr'
-----------------
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/0c/rcgf90kd6z9c7yc0p_tpffl81l1jxs/T/ipykernel_90245/1238206353.py in <module>
      2 os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
      3 import tensorflow as tf
----> 4 from bowsr.model.megnet import MEGNet
      5 from bowsr.optimizer import BayesianOptimizer
      6 from pymatgen.core.periodic_table import get_el_sp

ModuleNotFoundError: No module named 'bowsr'
-------------

I followed the instructions to install all the libraries. Please let me know if you can help.

**Comment by chc273** [comment]
@zhigangmei Hi, it should have been fixed now. Please check again.

**Comment by zhigangmei** [comment]
Still has the similar error.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/0c/rcgf90kd6z9c7yc0p_tpffl81l1jxs/T/ipykernel_92642/2761097269.py in <module>
----> 1 from maml.apps.bowsr.model.cgcnn import CGCNN
      2 from maml.apps.bowsr.optimizer import BayesianOptimizer
      3 from pymatgen.core.periodic_table import get_el_sp
      4 model = CGCNN()
      5 

ModuleNotFoundError: No module named 'maml.apps.bowsr'

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/0c/rcgf90kd6z9c7yc0p_tpffl81l1jxs/T/ipykernel_92641/3618893236.py in <module>
      2 os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
      3 import tensorflow as tf
----> 4 from maml.apps.bowsr.model.megnet import MEGNet
      5 from maml.apps.bowsr.optimizer import BayesianOptimizer
      6 from pymatgen.core.periodic_table import get_el_sp

ModuleNotFoundError: No module named 'maml.apps.bowsr'

**Comment by chc273** [comment]
make sure you install the lastest source code of maml after pulling the updates from github.

**Comment by zhigangmei** [comment]
Thanks. I can load model from appls.bowsr now.

Now comes another issue regarding loading module cgcnn. I found not find the instruction for install that module.

----> 4 model = CGCNN()
      5 
      6 def expected_radius(struct):

~/anaconda3/envs/maml/lib/python3.9/site-packages/monty/dev.py in decorated(*args, **kwargs)
     94         def decorated(*args, **kwargs):
     95             if not self.condition:
---> 96                 raise RuntimeError(self.message)
     97             return _callable(*args, **kwargs)
     98 

RuntimeError: cgcnn and torch are needed to use the CGCNN evaluator.
