### ISSUE TITLE
How to create the database

### ISSUE THREAD

**Issue by Levi22** [materialsvirtuallab/maml#334]
Hi there, big fan of the program,
 
I am struggling with figuring out how to create a .json database from which to train the model. Most of the example jupyter-notebooks start with loading in some data stored in a .json format, e.g. using "loadfn('./data/Mo/AIMD_NVT.json')"

I have tried simply using the to_json method from pymatgen.io.vasp.Vasprun , but when I try using loadfn() it keeps throwing errors like 
"__init__() got an unexpected keyword argument 'vasp_version' "

Can you please take me through how to create such a data file from VASP output?

Cheers

**Comment by chc273** [comment]
Hi @Levi22 

1) Load the vasprun file using `Vasprun` class in `pymatgen.io.vasp.outputs`.
```
from pymatgen.io.vasp.outputs import Vasprun
vrun = Vasprun('vasprun.xml')
```
2) 
The energy, force and stress are

```vrun.ionic_steps[-1]['e_wo_entrp’]
vrun.ionic_steps[-1][‘forces’]
vrun.ionic_steps[-1][’stress’]```

And the structure is 
```
vrun.ionic_steps[-1][’structure’]
```

Once you have all those info, you can train the model

**Comment by chc273** [comment]
@Levi22 

I have made an example https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/data/process_vasprun_to_mliap.ipynb 

the details may not be identical to the previously published papers, but the idea is the same, i.e., we want to get the structure, energy, force, and stress out of a vasprun.
