### ISSUE TITLE
LAMMPS pair_style compatibility for NNP (HDNNP)

### ISSUE THREAD

**Issue by yliu1240** [materialsvirtuallab/maml#341]
Hi, all!
It seems LAMMPS has updated its pair_style command for hdnnp. Running MAML with NNP gives errors on pair_style:
"""
        pair_style hdnnp cutoff keyword value ...
        pair_coeff * * elements
"""
which is different from previous:
"""
        pair_style nnp keyword value ...
        pair_coeff * * elements cutoff
"""
https://docs.lammps.org/pair_hdnnp.html

I'm not sure if the LAMMPS has other packages implementing NNP else than HDNNP.
If ML-HDNNP is the LAMMPS package for NNP, I guess the _nnp.py may need to be updated as well?
For pair_style and pair_coeff variables:
"""
        pair_style = (
                'pair_style        hdnnp {} dir "./" showew no showewsum 0 '
                "maxew 10000000 resetew yes cflength 1.8897261328 cfenergy 0.0367493254"
        )
        pair_coeff = "pair_coeff        * * {}"
""" (from line 37)

For write_param():
"""
        ff_settings = [self.pair_style.format(self.param.get("r_cut") + 1e-2), self.pair_coeff.format(" ".join(self.elements))]
""" (from line 704)
I'm not sure if I missed anything on this part?

Thanks a lot and have a nice day!

Best,

**Comment by JiQi535** [comment]
> Hi, all! It seems LAMMPS has updated its pair_style command for hdnnp. Running MAML with NNP gives errors on pair_style: """ pair_style hdnnp cutoff keyword value ... pair_coeff * * elements """ which is different from previous: """ pair_style nnp keyword value ... pair_coeff * * elements cutoff """ https://docs.lammps.org/pair_hdnnp.html
> 
> I'm not sure if the LAMMPS has other packages implementing NNP else than HDNNP. If ML-HDNNP is the LAMMPS package for NNP, I guess the _nnp.py may need to be updated as well? For pair_style and pair_coeff variables: """ pair_style = ( 'pair_style hdnnp {} dir "./" showew no showewsum 0 ' "maxew 10000000 resetew yes cflength 1.8897261328 cfenergy 0.0367493254" ) pair_coeff = "pair_coeff * * {}" """ (from line 37)
> 
> For write_param(): """ ff_settings = [self.pair_style.format(self.param.get("r_cut") + 1e-2), self.pair_coeff.format(" ".join(self.elements))] """ (from line 704) I'm not sure if I missed anything on this part?
> 
> Thanks a lot and have a nice day!
> 
> Best,

@yliu1240 Thanks! I have investigated this issue and found two officially supported `pair_style` for using NNP in LAMMPS. One is `hdnnp` [(https://docs.lammps.org/pair_hdnnp.html)](https://docs.lammps.org/pair_hdnnp.html), and the other is `nnp` [(https://compphysvienna.github.io/n2p2/interfaces/pair_nnp.html#pair-nnp)](https://compphysvienna.github.io/n2p2/interfaces/pair_nnp.html#pair-nnp). Both of them work. Our implementation is using the `nnp` as pair_style, whose installation and usage is well documented in the n2p2 documentation [(https://compphysvienna.github.io/n2p2/)](https://compphysvienna.github.io/n2p2/).

So `hdnnp` does not seem an "updated" `pair_style`, but a stand-alone `pair_style` in LAMMPS independent of n2p2. Since `hdnnp` in LAMMPS is equivalent to `nnp` in terms of LAMMPS simulations and not capable of NNP training, we now think that there is no need to switch the `pair_style`. 

Please let me know if this solves the issue. Thanks!

**Comment by yliu1240** [comment]
> > Hi, all! It seems LAMMPS has updated its pair_style command for hdnnp. Running MAML with NNP gives errors on pair_style: """ pair_style hdnnp cutoff keyword value ... pair_coeff * * elements """ which is different from previous: """ pair_style nnp keyword value ... pair_coeff * * elements cutoff """ https://docs.lammps.org/pair_hdnnp.html
> > I'm not sure if the LAMMPS has other packages implementing NNP else than HDNNP. If ML-HDNNP is the LAMMPS package for NNP, I guess the _nnp.py may need to be updated as well? For pair_style and pair_coeff variables: """ pair_style = ( 'pair_style hdnnp {} dir "./" showew no showewsum 0 ' "maxew 10000000 resetew yes cflength 1.8897261328 cfenergy 0.0367493254" ) pair_coeff = "pair_coeff * * {}" """ (from line 37)
> > For write_param(): """ ff_settings = [self.pair_style.format(self.param.get("r_cut") + 1e-2), self.pair_coeff.format(" ".join(self.elements))] """ (from line 704) I'm not sure if I missed anything on this part?
> > Thanks a lot and have a nice day!
> > Best,
> 
> @yliu1240 Thanks! I have investigated this issue and found two officially supported `pair_style` for using NNP in LAMMPS. One is `hdnnp` [(https://docs.lammps.org/pair_hdnnp.html)](https://docs.lammps.org/pair_hdnnp.html), and the other is `nnp` [(https://compphysvienna.github.io/n2p2/interfaces/pair_nnp.html#pair-nnp)](https://compphysvienna.github.io/n2p2/interfaces/pair_nnp.html#pair-nnp). Both of them work. Our implementation is using the `nnp` as pair_style, whose installation and usage is well documented in the n2p2 documentation [(https://compphysvienna.github.io/n2p2/)](https://compphysvienna.github.io/n2p2/).
> 
> So `hdnnp` does not seem an "updated" `pair_style`, but a stand-alone `pair_style` in LAMMPS independent of n2p2. Since `hdnnp` in LAMMPS is equivalent to `nnp` in terms of LAMMPS simulations and not capable of NNP training, we now think that there is no need to switch the `pair_style`.
> 
> Please let me know if this solves the issue. Thanks!

Hi! Thank you very much!
I see. It seems the HDNNP is the LAMMPS-published package library that tries to integrate N2P2 into LAMMPS, and the NNP one is the N2P2-published that integrates LAMMPS into N2P2. I guess if both libraries work, it'll be fine.
Thank you again!

Best,

**Comment by MTN8071** [comment]
Ohh I forgot to mention the issue .It goes like this ---> 
In file included from /home/salunke/LAMMPS/lammps-2Aug2023/build/styles/style_pair.h:16,
                 from /home/salunke/LAMMPS/lammps-2Aug2023/src/force.cpp:21:
/home/salunke/LAMMPS/lammps-2Aug2023/src/pair_nnp.h:17:10: fatal error: InterfaceLammps.h: No such file or directory
   17 | #include "InterfaceLammps.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lammps.dir/build.make:2715: CMakeFiles/lammps.dir/home/salunke/LAMMPS/lammps-2Aug2023/src/force.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1001: CMakeFiles/lammps.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
