### ISSUE TITLE
lattice not in supported kwargs ['lmp_exe']

### ISSUE THREAD

**Issue by zhangzhen507** [materialsvirtuallab/maml#361]
```
from maml.apps.pes._snap import SNAPotential
from pymatgen.core import Structure, Element
from maml.apps.pes._lammps import EnergyForceStress, ElasticConstant, DefectFormation

snap = SNAPotential.from_config(coeff_file='SNAPotential.snapcoeff', param_file='SNAPotential.snapparam')

Ni_conventional_cell = Structure.from_file('Ni_conventional.cif')
efs_calculator = EnergyForceStress(ff_settings=snap)
energy, forces, stresses = efs_calculator.calculate([Ni_conventional_cell])[0]
print('The predicted energy of Ni conventional cell is {} eV'.format(energy))
print('The predicted forces of Ni conventional cell is \n {} eV/Angstrom'.format(forces))

elastic_calculator = ElasticConstant(ff_settings=snap, lattice='fcc', alat=3.508)
C11, C12, C44, bulkmodulus = elastic_calculator.calculate()
print('The predicted C11, C12, C44, bulkmodulus are {}, {}, {}, {} GPa'.format(C11, C12, C44, bulkmodulus))

defect_calculator = DefectFormation(ff_settings=snap, specie='Ni', lattice='fcc', alat=3.508)
defect_formation_energy = defect_calculator.calculate()
print('The predicted defect formation energy is {} eV'.format(defect_formation_energy))
```

When I run this code, it has this error.

Traceback (most recent call last):
  File "/home/sdb/zzhen/2021/materialsvirtuallab/maml-2021.10.14/mvl_models/pes/Ni/snap/Ni_snap.py", line 13, in <module>
    elastic_calculator = ElasticConstant(ff_settings=snap, lattice='fcc', alat=3.508)
  File "/home/sdb/zzhen/2021/materialsvirtuallab/maml-2021.10.14/maml/apps/pes/_lammps.py", line 417, in __init__
    super().__init__(**kwargs)
  File "/home/sdb/zzhen/2021/materialsvirtuallab/maml-2021.10.14/maml/apps/pes/_lammps.py", line 87, in __init__
    raise TypeError("%s not in supported kwargs %s" % (str(i), str(self.allowed_kwargs)))
TypeError: lattice not in supported kwargs ['lmp_exe']

**Comment by chc273** [comment]
@zhangzhen507 Hi the interface has changed. Previously, the method was limited to running elastic constant on several types of lattices, for example, `fcc`, `bcc` etc. Now we changed it to be more general. 

When you initialize the instance of the class, you just need to specify `ff_settings`, then you pass your `structure` in the `calculate` method. Check this out https://github.com/materialsvirtuallab/maml/blob/a2dbb7ac66393d9248a7596772f30e322209b547/maml/apps/pes/_lammps.py#L379-L387
