### ISSUE TITLE
Data availability for Ensemble-Learned Spectra IdEntification (ELSIE) algorithm

### ISSUE THREAD

**Issue by Sangwon91** [materialsvirtuallab/maml#369]
Hello, 

Recently I have developed property predictive and spectra matching deep learning algorithm using **site averaged** K-edge XANES spectrum database from Materials Project. And I found that the site-wise might improve my model but unfortunately, I couldn't download site-wise K-edge spectrum from `MIRester`. So I have to download site-wise spectra from the legacy website by clicking download button. Downloading all XANES spectra in this way is impractical. L-edge data can be downloaded from the paper website (offered by figshare link). Is there  any way to download **site-wise**  K-edge XANES spectra?

I want compare my models with excellent results of your group.
1. Random Forest Models for Accurate Identification of Coordination Environments from X-Ray Absorption Near-Edge Structure
2. Automated generation and ensemble-learned matching of X-ray absorption spectra 

But without the database, the comparison might be wrong because my model is not trained with same database you used.

Thank you!

**Comment by yimingchen-eng** [comment]
Hi,
Thanks for your interest in our XANES works. The **site-wise** K-edge XANES spectra are also available through [figshare link](https://figshare.com/articles/dataset/K-edge_XANES_spectra_data/5678998). Just let me know if there is anything I could help.

**Comment by Sangwon91** [comment]
The download link works. I'm really happy to get the data.

I hope projects of your group goes well.

Thank you!
