### ISSUE TITLE
BOWSR MWE based on chemical formula

### ISSUE THREAD

**Issue by sgbaird** [materialsvirtuallab/maml#373]
Hi @chc273,

Again, nice work on BOWSR! I've been recommending BOWSR to a few people, but I'm realizing the implementation described in the Materials Today paper is not immediately obvious to me. IIRC, this involves swapping out the "correct" atoms for a similar chemical formula template (e.g. we have the CIF file for `Al2O3`, we want a crystal structure for `V2O3`, so we "swap" `Al` atoms with `V` atoms) and then running the optimizer.

Assuming my understanding is correct, do you mind sharing a MWE for the use-case described in the paper (i.e. create a relaxed structure using only a chemical formula)?

Sterling

**Comment by chc273** [comment]
@sgbaird thanks for your interest in our work！

You can use pymatgen for getting the structure predictions. THe `substitutor` should help.

https://github.com/materialsproject/pymatgen/blob/v2022.0.15/pymatgen/analysis/structure_prediction/substitutor.py

Once you have the predicted hypothetical structures, you can use this example for running the relaxation.

https://github.com/materialsvirtuallab/maml/blob/master/notebooks/bowsr/megnet_example.ipynb
