### ISSUE TITLE
positive pe/atom, multi-element system: SNAP

### ISSUE THREAD

**Issue by Rana-Phy** [materialsvirtuallab/maml#378]
Dear Developers,

I am training SNAP for a ternary system containing [Ti, Si, and C](https://materialsproject.org/materials/mp-5659/).

1. Using distorted (with or without NVT data) training data set of this system I am seeing that computed potential energy/atom is huge (order of 10^6) and negative for Ti, C; positive for Si!.
2. However, the total energy of the perfect system is consistent with DFT.
3. The obtained SNAP can reproduce many properties calculated by DFT like lattice parameter, elastic constant, stacking fault energy.
4. To get reasonable pe/atom, I add elemental (bulk) data for each component. Now the pe/atom is in order of 10^1, but still, I am getting positive pe for Si.

I guess I am (by maml code) somehow managing the total energy of my system with non-physical pe/atom by making two more negative and one positive.
I actually tried a lot with different combinations of training data set and looking for the pe/atom which is physically meaningful (negative).
Is there any way to constrain the snap coeff.  during training which will at least ensure negative pe/atom?
Or how can I resolve this issue for any multi-component systems?

I will be waiting to hear from you.

Best regards,
Rana

**Comment by chc273** [comment]
@Rana-Phy  thanks for the comments. I think the optimization finds the solutions with one positive value for bulk energy to be the most probable solution. It is from the data you chose rather than the code mandating such behavior. 

An easy test would be to copy the bulk elemental data in the training a few times. This is essentially adding a large weight to those data points to make sure that the model predicts the correct elemental energy.

**Comment by chc273** [comment]
@Rana-Phy it is also possible to constrain the snap coeff. Basically, the snap coeff is just the coefficients fitted from linear regression. You can put the constraints that you like fairly easily to the linear fitting part, but that requires you to modify some part in the code.

**Comment by Rana-Phy** [comment]
@chc273 Thanks for your quick reply. I have a quick check on my data set.
Could it come from the mixing Ti and Ti_sv versions (VASP potential)?
I have used Ti PAW for large structures (100-200 atom cases) for faster calculation.
Other DFT calculations are done with Ti_sv.
If there is any way or tips for energy correction manually due to PAW version mixing kindly let us know.

**Comment by chc273** [comment]
@Rana-Phy  ah, this could be a problem. The abs energy can be different using different pseudopotentials. Please keep them consistent.

**Comment by Rana-Phy** [comment]
@chc273 It seems like fitsnap code has a tool for shifting energy.
https://github.com/FitSNAP/FitSNAP/tree/master/tools
