### ISSUE TITLE
Query regarding parameters

### ISSUE THREAD

**Issue by mind-dime** [materialsvirtuallab/maml#406]
Hi, I'm fairly new to using the SNAP POTENTIAL in maml. I'd like to know what is the meaning of w and r in element_profile. Also the rcutfac in BispectrumCoefficients() is same as r_c parameter discussed in the seminal papers of SNAP?

**Comment by deadsummer** [comment]
Hi, mind-dime!
All parameters are described well at https://docs.lammps.org/compute_sna_atom.html
For me it was enough information to understand the thing.

**Comment by mind-dime** [comment]
> Hi, mind-dime!
> 
> All parameters are described well at https://docs.lammps.org/compute_sna_atom.html
> 
> For me it was enough information to understand the thing.

Thanks for your reply @deadsummer . That helped. I now have vasp output OUTCAR files of my required structures. Can you help me in converting them to formats that can be input to the transform function of "Bispectrum_coefficients"?

**Comment by JiQi535** [comment]
> > Hi, mind-dime!
> > All parameters are described well at https://docs.lammps.org/compute_sna_atom.html
> > For me it was enough information to understand the thing.
> 
> Thanks for your reply @deadsummer . That helped. I now have vasp output OUTCAR files of my required structures. Can you help me in converting them to formats that can be input to the transform() function of "Bispectrum_coefficients"?
> 
> Solved ( for future reference): read poscar/contcar as structure ( from pymatgen.core import Structure ; file= Structure.from_file("Poscar");).
> 
> Now the important part, convert it to a list(even if for one structure) and supply that as an argument to the transform() function.

Hi @mind-dime, I believe this issue can be solved with my reply for the issue [https://github.com/materialsvirtuallab/maml/issues/413](https://github.com/materialsvirtuallab/maml/issues/413).
