### ISSUE TITLE
Converting vasp output for Bispectrum_coefficients.

### ISSUE THREAD

**Issue by mind-dime** [materialsvirtuallab/maml#413]
I have vasp output OUTCAR/CONTCAR/XDATCAR files of my required structures obtained from MOLECULAR DYNAMICS. Can you help me in converting them to format that can be input to the transform() function of "Bispectrum_coefficients"?

**Comment by JiQi535** [comment]
> I have vasp output OUTCAR/CONTCAR/XDATCAR files of my required structures obtained from MOLECULAR DYNAMICS. Can you help me in converting them to format that can be input to the transform() function of "Bispectrum_coefficients"?

Hi @mind-dime, for collecting VASP results into a data structure that pes modules in maml can directly read, please refer to this solved issue: [https://github.com/materialsvirtuallab/maml/issues/334](https://github.com/materialsvirtuallab/maml/issues/334)

After collecting the VASP results, MLIAPs can be trained as shown in these notebooks: [https://github.com/materialsvirtuallab/maml/tree/master/notebooks/pes](https://github.com/materialsvirtuallab/maml/tree/master/notebooks/pes)

And to directly answer your question about using the transform() method, this method takes a list of pymatgen structures as the only argument. And the pymatgen structure list is already obtained as part of the information collected from VASP results.
