### ISSUE TITLE
BispectrumCoefficients error

### ISSUE THREAD

**Issue by AyeshaUlde** [materialsvirtuallab/maml#417]
Hello, 

I am getting "TypeError: expected str, bytes or os.PathLike object, not NoneType" when I try to compute the BispectrumCoefficients in the feature_analysis notebook provided on nanoHUB. 

![Screenshot (239)](https://user-images.githubusercontent.com/65012901/158053961-b9b24522-2764-4b06-b981-13dc94275618.png)
![Screenshot (241)](https://user-images.githubusercontent.com/65012901/158054177-ed2a1cba-cf74-4966-ab54-6be040427985.png)
![Screenshot (244)](https://user-images.githubusercontent.com/65012901/158054224-ffe3ac7d-870c-408a-aab2-74c5dcf95721.png)

How can I fix this error?

**Comment by JiQi535** [comment]
Hello, from the error message, the "lmp_exe" variable was having a NoneType. Would you please make sure you have a lammps executable in the path where your system has access to it in any location? The lammps executable should have a name of "lmp_serial" or "lmp_mpi" or "lmp_g++_serial" or "lmp_g++_mpich" or "lmp_intel_cpu_intelmpi".

**Comment by AyeshaUlde** [comment]
I have "lmp_mpi " and "lmp_serial" in the bin of the conda environment where I have installed maml and the required packages. The system has execute permissions for both the executables but when I run which("lmp_mpi") or which("lmp_serial"), no path is returned.

**Comment by JiQi535** [comment]
> I have "lmp_mpi " and "lmp_serial" in the bin of the conda environment where I have installed maml and the required packages. The system has execute permissions for both the executables but when I run which("lmp_mpi") or which("lmp_serial"), no path is returned.

Can you double check that the "lmp_mpi" executable is added to a directory in your $PATH list? If so, which("lmp_mpi") should be able to find the full path of the executable. For example, which("g++") should return the path for g++ executable, and then you can copy the "lmp_mpi" to the same folder as g++ executable on your machine, which should solve this issue.

**Comment by JiQi535** [comment]
> I have "lmp_mpi " and "lmp_serial" in the bin of the conda environment where I have installed maml and the required packages. The system has execute permissions for both the executables but when I run which("lmp_mpi") or which("lmp_serial"), no path is returned.

If necessary, you may refer to this post for $PATH and executables. [https://askubuntu.com/questions/551990/what-does-path-mean](https://askubuntu.com/questions/551990/what-does-path-mean)

**Comment by AyeshaUlde** [comment]
> > I have "lmp_mpi " and "lmp_serial" in the bin of the conda environment where I have installed maml and the required packages. The system has execute permissions for both the executables but when I run which("lmp_mpi") or which("lmp_serial"), no path is returned.
> 
> Can you double check that the "lmp_mpi" executable is added to a directory in your $PATH list? If so, which("lmp_mpi") should be able to find the full path of the executable. For example, which("g++") should return the path for g++ executable, and then you can copy the "lmp_mpi" to the same folder as g++ executable on your machine, which should solve this issue.

That worked. Thank you!
