### ISSUE TITLE
Getting the snapcoeff and snapparam files.

### ISSUE THREAD

**Issue by mind-dime** [materialsvirtuallab/maml#419]
Dear all, how can I get the snapcoeff and snapparam files from within maml to be used with LAMMPS? 

Also, if I want to calculate properties using a developed snap model for a multi element system, how to proceed?  Suppose I want to get elastic constants for NbMoTaW with the potential object named "NMTW", in that case how to initiate the ElasticConstant() calculator? I want to get the constants for bulk NbMoTaW and not individual elements.

**Comment by shyuep** [comment]
We have written notebooks that shows how to use the snap coeffs calculated. See https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/snap/example.ipynb . Using it with the NbTaMoW is the same.

**Comment by shyuep** [comment]
You can download the snapparam and coeff files. And you can certainly paste them into your input files for LAMMPS. All this code is doing is to generate the input files and run LAMMPS automatically.

**Comment by JiQi535** [comment]
> @shyuep thanks a lot. Is there any way to export the .snapparam and.snapcoeff files so that I can use it independently with LAMMPS, or that has to be done manually?

With an object of SNAP loaded or fitted with maml, assuming that it has is named as "theSNAP",  `theSNAP.write_param()` will write the parameters to files.

**Comment by mind-dime** [comment]
Can you please tell me where to write the path to the folder where I want to save the files? I mean write_param() takes any argument for filepath as input? Because if I write snap.write_param() ( snap is the fitted object) only two string files are getting outputted?

**Comment by JiQi535** [comment]
@mind-dime The two output files for SNAP potentials should be sufficient to define the parameters and to be used by LAMMPS. They are enough, aren't they? 

From the definition,  we don't allow customized folder path for the parameter writing, so the two files will be written to the working folder with predefined names. We don't have issues using the SNAP, please let us know if you do.
