### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by knc6** [materialsvirtuallab/maml#491]
Thank you for your work on preparing and sharing the benchmark datasets.

But, I couldn't reproduce the results in the paper.

I tried the SNAP potential for Silicon, and a draft version of the notebook is kept here:
https://gist.github.com/knc6/10b7ec5c2171210cc646e7ffca55b5a0

I get an RMSE on energies as 0.03 eV/atom but in the [original paper](https://doi.org/10.1021/acs.jpca.9b08723), the RMSE is much less (0.00806 eV/atom).

**Comment by JiQi535** [comment]
Hi @knc6 , for SNAP training, you need to tune the data weights to get optimal training errors. The Supplementary Information for the paper you are referring to  has provided the optimized weights. In your notebook, you are just setting 100 and 1 as energy and force weights.
