### ISSUE TITLE
a Code running error (Example for MTP fitting)

### ISSUE THREAD

**Issue by Guancred** [materialsvirtuallab/maml#505]
Hi, we try to train a MTP according to the example, but a code running error occurs as following. 

![image](https://user-images.githubusercontent.com/91767936/221335520-646d35ac-8fac-4cf0-822b-8020cc662c57.png)

Whether we need to install some other packages? 

Looking forward to your reply!

**Comment by JiQi535** [comment]
Hello, as in the error message, the `mlp` executable implemented in the MLIP package [(https://mlip.skoltech.ru)](https://mlip.skoltech.ru) should be installed and put into the $PATH so that it can be found.

**Comment by Guancred** [comment]
Hi, eventually, I have installed the MLIP and put into the $PATH, as shown following picture:




However, there is the same error occurred.




Best
Chaohong


从 Windows 版邮件发送

发件人: JiQi535
发送时间: 2023年2月26日 3:50
收件人: materialsvirtuallab/maml
抄送: Guancred; Author
主题: Re: [materialsvirtuallab/maml] a Code running error (Example for MTPfitting) (Issue #505)

Hello, as in the error message, the mlp executable implemented in the MLIP package (https://mlip.skoltech.ru) should be installed and put into the $PATH so that it can be found.

**Comment by Guancred** [comment]
Hello,
The error in the last email has been solved by add the $PATH of mlp to the source code of _mtp.py, but there is a new error occurred :


And the corresponding python code:


Thank you so much for your time,

从 Windows 版邮件发送

发件人: JiQi535
发送时间: 2023年2月26日 3:50
收件人: materialsvirtuallab/maml
抄送: Guancred; Author
主题: Re: [materialsvirtuallab/maml] a Code running error (Example for MTPfitting) (Issue #505)

Hello, as in the error message, the mlp executable implemented in the MLIP package (https://mlip.skoltech.ru) should be installed and put into the $PATH so that it can be found.

**Comment by JiQi535** [comment]
@Guancred Sorry, but I cannot see the error message either through email or on github.

**Comment by Guancred** [comment]
> @Guancred Sorry, but I cannot see the error message either through email or on github.

Hello, the error message is :
![image](https://user-images.githubusercontent.com/91767936/222022896-61350623-dfee-44d7-9518-808bf64a5690.png)
And the corresponding python code:
![image](https://user-images.githubusercontent.com/91767936/222023052-a38c78e7-12a7-41fe-86bd-a33025e12935.png)

**Comment by JiQi535** [comment]
Hi, as the error code indicates, the stress data `train_stresses` has a data structure not compatible with what our code tries to read. 
1. would you please try to set `test_stresses=None`?
2. For stress, you can follow the first session of [this notebook](https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/snap/example_with_stress.ipynb) to load it properly. Then your problem should be solved.

**Comment by Guancred** [comment]
> Hi, as the error code indicates, the stress data `train_stresses` has a data structure not compatible with what our code tries to read.
> 
> 1. would you please try to set `test_stresses=None`?
> 2. For stress, you can follow the first session of [this notebook](https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/snap/example_with_stress.ipynb) to load it properly. Then your problem should be solved.

Hi, thank you for your time, 
I have updated the code according to "example_with_strss.ipynb", while i found that:
the "virial_stress" in this example including six elements in the list when we printed it as follows:
![image](https://user-images.githubusercontent.com/91767936/222626476-797fbf0b-4192-4a7c-8bac-2c9b3de41a2b.png)

However, when i obtained the data.json file by the code "process_vasprun_to_mliap.ipynb", the "virial_stress" is different:
![1](https://user-images.githubusercontent.com/91767936/222627300-811052e5-e475-4c75-9bfd-e6870d74962a.png)

Therefore, the following error occurred.
![image](https://user-images.githubusercontent.com/91767936/222627392-9a2df584-0581-4bc7-9cdb-f91f9c1e355f.png)

Besides, whether it is necessary for training a MTP to set "train_stresses"?

**Comment by caolz** [comment]
I have the same problem, when loading Ni-Mo data the pressure is like this "stress": [147.81627907, 136.51634565, 139.00238213, 14.66967488, 12.59437751, 11.17493306]. But when loading Si data the pressure is like this "stress": [[27.098935, 0.0, 0.0], [0.0, 27.098935, 0.0], [0.0, 0.0, -53.18308907]]. I had the same problem when I used [https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/snap/example_with_stress.ipynb](url) . How can I fix it?

**Comment by JiQi535** [comment]
Hi! The stress data in the Ni-Mo dataset has 6 elements that are unique, in the order of xx, yy, zz, xy, yz, xz. The `pool_from` function in maml takes this 6-element stress as input in the [training notebook with stress](https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/snap/example_with_stress.ipynb). So one extra step of processing is needed after loading stress from VASP to format the stress as a 6-element vector. @Guancred The same processing is required for the Si data @caolz. 

This processing of a 3x3 stress array (e.g., "`stress`") to a 6-element vector  (e.g., "`virial_stress`") can be done like below:
` virial_stress = stress[(0, 1, 2, 0, 1, 0), (0, 1, 2, 1, 2, 2)].tolist()`

Hope that helps!

**Comment by Guancred** [comment]
Hi! Thank you very much, the process is so clear. Additionally, I want to try the MTP of  Na2.25Y0.25Zr0.75Cl6, but the structure is difficult to buid, Would you mind sending me a structure file? 

Thanks.

从 Windows 版邮件发送

发件人: JiQi535
发送时间: 2023年8月7日 9:52
收件人: materialsvirtuallab/maml
抄送: Guancred; Mention
主题: Re: [materialsvirtuallab/maml] a Code running error (Example for MTPfitting) (Issue #505)

Hi! The stress data in the Ni-Mo dataset has 6 elements that are unique, in the order of xx, yy, zz, xy, yz, xz. The pool_from function in maml takes this 6-element stress as input in the training notebook with stress. So one extra step of processing is needed after loading stress from VASP to format the stress as a 6-element vector. @Guancred The same processing is required for the Si data @caolz.
This processing of a 3x3 stress array (e.g., "stress") to a 6-element vector (e.g., "virial_stress") can be done like below:
virial_stress = stress[(0, 1, 2, 0, 1, 0), (0, 1, 2, 1, 2, 2)].tolist()
Hope that helps!

**Comment by shyuep** [comment]
Sorry, but while we are happy to advise on how to make the code work, we cannot do research on behalf of other people. Generating and supplying a structure file falls under that category.

**Comment by JiQi535** [comment]
@Guancred If it is related to our previous publications, please kindly email the corresponding author for the specific structures of interest. Thanks for the understanding.
