### ISSUE TITLE
How to use potential in lammps?

### ISSUE THREAD

**Issue by Jeffery-Li0513** [materialsvirtuallab/maml#511]
If Iwant to use a potential generated by maml, how should I define pair_style and pair_coeff parameter in lammps?

**Comment by JiQi535** [comment]
Hi @Jeffery-Li0513, the setting of `pair_style` and `pair_coeff` of potentials are always the same as those defined by the developers of those potentials, and maml does not have any change to these settings. 

All the parameter files of potentials trained by maml can be stored with the `write_param` function of a `LammpsPotential` object, and you can set the respective `pair_style` and `pair_coeff` to read those parameter files. 

As an example, maml sets `pair_style` and `pair_coeff` for lammps input files of SNAP this way: https://github.com/materialsvirtuallab/maml/blob/0e98a5541ff12000b3cdbffae71367a57bd4fbda/maml/apps/pes/_snap.py#L32-L33
Where the coeff_file and param_file can be written out with the `write_param` function of a `SNAPotential` from maml.
