### ISSUE TITLE
The problem of model training efficiency

### ISSUE THREAD

**Issue by caolz** [materialsvirtuallab/maml#552]
I use MTP, here's my code:

`from pymatgen.core import Structure
from monty.serialization import loadfn
from maml.apps.pes import MTPotential

data = loadfn('TlVSe-all.json')
train_structures = [d['structure'] for d in data]
train_energies = [d['outputs']['energy'] for d in data]
train_forces = [d['outputs']['forces'] for d in data]
train_stresses = [d['outputs']['stress'] for d in data]

mtp = MTPotential()

mtp.train(train_structures=train_structures, train_energies=train_energies,
          train_forces=train_forces, train_stresses = None, max_dist=5, stress_weight=0)

mtp.write_param(fitted_mtp='fitted.mtp')`

MTP compiles the mpi version, but how does it work? There is only a single core for training.

**Comment by JiQi535** [comment]
Hi, this is a similar question as discussed in issue https://github.com/materialsvirtuallab/maml/issues/216. 

Following the previous discussions, you can add in mpirun or equivalent comments working on your clusters to make parallel training. The modifications should be added in below lines for MTP, and the maml should be reinstalled.
https://github.com/materialsvirtuallab/maml/blob/44066d1559c43ea5d733c27501097dcc09c66f40/maml/apps/pes/_mtp.py#L613-L629

**Comment by caolz** [comment]
Nice, I see how to modify it. Thank you.
