### ISSUE TITLE
MTP example notebook (issue with imports)

### ISSUE THREAD

**Issue by michaelmacisaac** [materialsvirtuallab/maml#560]
Hi,
I am wanting to use maml to develop an MTP potential, when I try to use the example notebook I get the following error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 from maml.apps.pes import MTPotential
      3 mtp = MTPotential()

File [~/.local/lib/python3.11/site-packages/maml/apps/pes/__init__.py:7](https://vscode-remote+tunnel-002bhipergator.vscode-resource.vscode-cdn.net/home/michaelmacisaac/blue_subhash/michaelmacisaac/SiC/maml/tutorial/~/.local/lib/python3.11/site-packages/maml/apps/pes/__init__.py:7)
      4 """This package contains PotentialMixin classes representing Interatomic Potentials."""
      6 from ._base import Potential, PotentialMixin  # noqa
----> 7 from ._gap import GAPotential  # noqa
      8 from ._lammps import DefectFormation  # noqa
      9 from ._lammps import ElasticConstant  # noqa

File [~/.local/lib/python3.11/site-packages/maml/apps/pes/_gap.py:14](https://vscode-remote+tunnel-002bhipergator.vscode-resource.vscode-cdn.net/home/michaelmacisaac/blue_subhash/michaelmacisaac/SiC/maml/tutorial/~/.local/lib/python3.11/site-packages/maml/apps/pes/_gap.py:14)
     12 import numpy as np
     13 from monty.io import zopen
---> 14 from monty.os.path import which
     15 from monty.serialization import loadfn
     16 from monty.tempfile import ScratchDir

ImportError: cannot import name 'which' from 'monty.os.path' (/home/michaelmacisaac/.local/lib/python3.11/site-packages/monty/os/path.py) 

Assistance resolving this issue would be appreciated

**Comment by michaelmacisaac** [comment]
Fix for this issue:
Replace all "monty.os.path import which" with " from shutil import which"

**Comment by JiQi535** [comment]
@michaelmacisaac Thanks for raising this issue. Since [Nov 2022](https://github.com/materialsvirtuallab/maml/commit/6a3159a4e1673fe5edcb9fe120bc440a34167112), the maml codes on github is already using "from shutil import which". If you download the latest version of maml from github and install with pip, then this issue should no longer exists.

@shyuep Hi Shyue Ping, would you help to update the released version of maml on pypi? The current version is updated in Sep 2022.
