### ISSUE TITLE
MLIP MTP notebook

### ISSUE THREAD

**Issue by michaelmacisaac** [materialsvirtuallab/maml#561]
Hi,
I have encountered a few issues while trying to follow the example notebooks, but currently I can not resolve the issue pertaining to the mlp executable being available. I load it into $PATH and it is visible when I perform the command: "echo $PATH." However, I am still receiving the following error:
mlp has not been found.\n', 'Please refer to https://mlip.skoltech.ru/', 'for further detail.

Any help with this would be greatly appreciated. I saw a previous post about changing some parts of the source code but it did not help.

**Comment by shyuep** [comment]
Unfortunately this does not give us much to go on. I suggest you contact the mlp developers to debug the problem.

**Comment by michaelmacisaac** [comment]
I am confused, how would reaching out to the mlp developers aid in resolving the problem with 'maml'? What other information can I provide to aid in further understanding the issue. If it is any help, the error I mentioned occurs when I attempt to train a model in the example notebook pertaining to MTP. The path to this notebook is: notebooks/pes/mtp/example.ipynb

**Comment by shyuep** [comment]
You gave us a one-liner error message. That message only says that the notebook cannot find the mlp executable. Either the mlp executable itself is not in your path or it is not compiled properly. The error message is not related to the functioning of the maml code at all.

**Comment by michaelmacisaac** [comment]
I see your point, I should have provided more context.
Recently I used the mlp executable to train a potential following a tutorial on the mlp gitlab. With the executable working I assume it is compiled correctly. 
The next reason for it failing is that it is not in the path, but it appears in the path when I run: "echo $PATH."
Do you have any recommendations for work arounds of this issue. I am adding the path variable via the following command: export PATH=$PATH:~/mlip-2/bin/mlp 
Thanks!

**Comment by JiQi535** [comment]
@michaelmacisaac Can you try PATH=$PATH:~/mlip-2/bin/ instead?

**Comment by michaelmacisaac** [comment]
Hi,
I followed your suggestions, but the error persists. Here is the output of echo $PATH"


/home/michaelmacisaac/.conda/envs/maml/bin:~./mlip-2/bin/mlp:/opt/slurm/bin:/home/michaelmacisaac/.vscode/cli/servers/Stable-6c3e3dba23e8fadc360aed75ce363ba185c49794/server/bin/remote-cli:/apps/ufrc/ufhpc/bin:/apps/git/2.30.1/bin:/apps/nano/2.8.2/bin:/apps/ufrc/bin:/opt/slurm/bin:/home/michaelmacisaac/miniconda3/condabin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/bin:/opt/dell/srvadmin/bin:/home/michaelmacisaac/bin/atomsk:/home/michaelmacisaac/bin:/apps/conda/23.7.2/bin:/home/michaelmacisaac/bin/atomsk:/home/michaelmacisaac/mlip-2/bin/mlp:/home/michaelmacisaac/mlip-2/bin/mlp:/home/michaelmacisaac/mlip-2/bin/


Do you see anything out of the ordinary? The mlp executable are near the end. 
My process for adding these variables to path has been executing the "export" command in my VSCode terminal, then attempting to run the jupyter cell notebooks.
