### ISSUE TITLE
Aout virial_stress data

### ISSUE THREAD

**Issue by yufeib** [materialsvirtuallab/maml#61]
Why does the function **convert_docs()** in /maml/utils/_data_conversion.py not handle virial_stress data? 
Add how can I train with virial_stress data? 
Thank you!

**Comment by chc273** [comment]
@yufei233 I believe the stress was in the potential fitting in https://github.com/materialsvirtuallab/mlearn, we will migrate it to maml in future release. @YunxingZuo could you please take a look, thanks.

**Comment by YunxingZuo** [comment]
@yufeib Hi,

Thanks for the comment. We have added include_stress argument to the convert_docs method. For further details of training potential with virial stress data, please take a look at the new [example notebook](https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/snap/example_with_stress.ipynb).

**Comment by yufeib** [comment]
Thanks !
