### ISSUE TITLE
Switch to Github Actions

### ISSUE THREAD

**Issue by shyuep** [materialsvirtuallab/maml#75]
Instead of using CircleCI, we will be moving to github actions henceforth for testing and linting.

1. Pls make sure all linting passes, including pylint.
2. Pls add a lammps executable for Ubuntu so that we can test the PES.

We will disable the CircleCI once all tests pass.

**Comment by shyuep** [comment]
I am assigning @YunxingZuo to coordinate all necessary efforts.

**Comment by shyuep** [comment]
Incidentally, I am not sure why the testing is failing on symbolic stuff. If there are required packages, these needs to be in requirements.txt or requirements-optional.txt or something. Adding ti manually to the CircleCI file is sloppy.

**Comment by w6ye** [comment]
Working on fixing it

**Comment by shyuep** [comment]
@chc273 Pls do not --exit-zero pylint. I want the code to pass pylint in ALL cases.

**Comment by chc273** [comment]
> @chc273 Pls do not --exit-zero pylint. I want the code to pass pylint in ALL cases.

ok, will fix it.

**Comment by shyuep** [comment]
For import order, the easiest way to quickly fix the code is to use Pycharm Code->Optimize Imports. That usually resolves most of the errors in a large number of cases.

**Comment by chc273** [comment]
ok, thanks @shyuep
